import React, { createContext, useContext, useState } from 'react';

export const translations = {
  en: {
    appName: 'இnaippu',
    logout: 'Logout', loading: 'Loading...', submit: 'Submit', cancel: 'Cancel',
    save: 'Save', next: 'Next', back: 'Back', edit: 'Edit', delete: 'Delete',

    citizenOverview: 'My Dashboard',
    serviceApplications: 'Service Applications',
    activeGrievances: 'Active Complaints',
    needHelp: 'Need Help?',
    needHelpDesc: "Submit a complaint or apply for a government certificate — we'll guide you.",
    newGrievance: 'Report a Problem',
    applyService: 'Apply for Service',
    myApplications: 'My Applications',
    myGrievances: 'My Complaints',
    overview: 'Overview',

    lifeEvents: 'What do you need today?',
    lifeEventsDesc: 'Choose your situation — we\'ll show the right services',
    birthChild: 'Birth of a Child',
    birthChildDesc: 'Birth certificate, vaccination records',
    deathFamily: 'Death in Family',
    deathFamilyDesc: 'Death certificate, property transfer',
    incomeProof: 'Need Income Proof',
    incomeProofDesc: 'Income certificate, community certificate',
    propertyMatters: 'Property Matters',
    propertyMattersDesc: 'Property tax, water connection',
    roadIssue: 'Road / Water Issue',
    roadIssueDesc: 'Report infrastructure problems',
    otherHelp: 'Something Else',
    otherHelpDesc: 'Browse all services',

    serviceApplication: 'Service Application',
    serviceApplicationDesc: 'Apply for government certificates and services.',
    serviceType: 'What do you need?',
    department: 'Department',
    processingOfficer: 'Processing Officer',
    applicationDetails: 'Tell us more',
    applicationDetailsPlaceholder: 'Describe your requirement in detail...',
    supportingDocs: 'Supporting Documents',
    selectService: 'Choose a service...',
    chooseDept: 'Choose department...',
    noOfficers: 'No officers available for this area',
    slaNote: 'Typical resolution',
    slaMax: 'Statutory maximum',
    days: 'days',

    newGrievanceTitle: 'Report a Problem',
    newGrievanceDesc: "Tell us what's wrong — an officer will be assigned automatically.",
    complaintCategory: 'Type of Problem',
    selectCategory: 'What is the issue?',
    routesTo: 'Goes to',
    autoAssignNote: 'An officer will be automatically assigned based on your area.',
    grievanceSubmitted: 'Complaint Registered!',
    redirecting: 'Taking you to your complaints...',

    step1: 'Your Details', step2: 'Problem Details', step3: 'Documents', step4: 'Review & Submit',

    statusPending: 'Received',
    statusInProgress: 'Being Reviewed',
    statusResolved: 'Resolved',
    statusRejected: 'Rejected',
    statusDescPending: 'Your complaint has been received and is waiting to be assigned.',
    statusDescInProgress: 'An officer is currently reviewing your complaint.',
    statusDescResolved: 'Your complaint has been resolved.',
    statusDescRejected: 'Your complaint could not be processed.',
    officerRemark: "Officer's Response",
    submittedOn: 'Submitted on',
    refNumber: 'Reference No.',

    draftSaved: 'Draft saved automatically',
    continueDraft: 'Continue where you left off?',
    discardDraft: 'Start fresh',

    notifications: 'Notifications',
    noNotifications: 'No new notifications',
    markAllRead: 'Mark all as read',
    liteMode: 'Lite Mode',

    joinPlatform: 'Welcome to இnaippu',
    joinDesc: 'Your single window for all government services',
    citizenPortal: 'I am a Citizen',
    citizenPortalDesc: 'Apply for services, track applications, report problems.',
    officerPortal: 'I am a Government Officer',
    officerPortalDesc: 'Manage requests and respond to citizen complaints.',
    fullName: 'Full Name',
    fullNamePlaceholder: 'As per your ID card',
    aadhaarNumber: 'Aadhaar Number',
    password: 'Password',
    passwordHint: 'Minimum 6 characters',
    createAccount: 'Create Account',
    submitVerification: 'Submit for Verification',
    alreadyHaveAccount: 'Already registered?',
    loginHere: 'Login here',
    pendingTitle: 'Request Received',
    pendingDesc: 'Your registration is pending admin approval. You will be notified once verified.',
    backToLogin: 'Back to Login',

    trackTitle: 'Track Your Complaint',
    trackDesc: 'Enter your complaint ID — no login needed',
    trackPlaceholder: 'Paste your complaint ID...',
    trackButton: 'Check Status',
    notFound: 'No complaint found with this ID.',
    assignedTo: 'Assigned to',
    dept: 'Department',
    noResults: 'No records found.',
  },

  ta: {
    appName: 'இணைப்பு',
    logout: 'வெளியேறு', loading: 'ஏற்றுகிறது...', submit: 'சமர்ப்பி', cancel: 'ரத்து',
    save: 'சேமி', next: 'அடுத்து', back: 'திரும்பு', edit: 'திருத்து', delete: 'நீக்கு',

    citizenOverview: 'என் டாஷ்போர்டு',
    serviceApplications: 'சேவை விண்ணப்பங்கள்',
    activeGrievances: 'செயலில் உள்ள புகார்கள்',
    needHelp: 'உதவி தேவையா?',
    needHelpDesc: 'புகார் தெரிவிக்கவும் அல்லது சான்றிதழுக்கு விண்ணப்பிக்கவும்.',
    newGrievance: 'பிரச்சனை தெரிவி',
    applyService: 'சேவைக்கு விண்ணப்பி',
    myApplications: 'என் விண்ணப்பங்கள்',
    myGrievances: 'என் புகார்கள்',
    overview: 'கண்ணோட்டம்',

    lifeEvents: 'இன்று என்ன தேவை?',
    lifeEventsDesc: 'உங்கள் தேவையை தேர்ந்தெடுங்கள் — சரியான சேவைகளை காட்டுவோம்',
    birthChild: 'குழந்தை பிறப்பு',
    birthChildDesc: 'பிறப்பு சான்றிதழ், தடுப்பூசி பதிவு',
    deathFamily: 'குடும்பத்தில் மரணம்',
    deathFamilyDesc: 'இறப்பு சான்றிதழ், சொத்து பரிமாற்றம்',
    incomeProof: 'வருமான சான்று தேவை',
    incomeProofDesc: 'வருமான சான்றிதழ், சமூக சான்றிதழ்',
    propertyMatters: 'சொத்து விவகாரங்கள்',
    propertyMattersDesc: 'சொத்து வரி, தண்ணீர் இணைப்பு',
    roadIssue: 'சாலை / தண்ணீர் பிரச்சனை',
    roadIssueDesc: 'உள்கட்டமைப்பு பிரச்சனைகளை தெரிவிக்கவும்',
    otherHelp: 'வேறு ஏதாவது',
    otherHelpDesc: 'அனைத்து சேவைகளையும் பார்க்கவும்',

    serviceApplication: 'சேவை விண்ணப்பம்',
    serviceApplicationDesc: 'அரசு சான்றிதழ்கள் மற்றும் சேவைகளுக்கு விண்ணப்பிக்கவும்.',
    serviceType: 'என்ன தேவை?',
    department: 'துறை',
    processingOfficer: 'அலுவலர்',
    applicationDetails: 'மேலும் விவரங்கள்',
    applicationDetailsPlaceholder: 'உங்கள் தேவையை விரிவாக விவரிக்கவும்...',
    supportingDocs: 'ஆவணங்கள்',
    selectService: 'சேவையை தேர்ந்தெடுக்கவும்...',
    chooseDept: 'துறையை தேர்ந்தெடுக்கவும்...',
    noOfficers: 'இந்த பகுதியில் அலுவலர்கள் இல்லை',
    slaNote: 'வழக்கமான தீர்வு நேரம்',
    slaMax: 'சட்டப்பூர்வ அதிகபட்சம்',
    days: 'நாட்கள்',

    newGrievanceTitle: 'பிரச்சனை தெரிவி',
    newGrievanceDesc: 'என்ன பிரச்சனை என்று சொல்லுங்கள் — அலுவலர் தானாக நியமிக்கப்படுவார்.',
    complaintCategory: 'பிரச்சனையின் வகை',
    selectCategory: 'என்ன பிரச்சனை?',
    routesTo: 'அனுப்பப்படும் இடம்',
    autoAssignNote: 'உங்கள் பகுதி மற்றும் பிரச்சனை வகையின் அடிப்படையில் அலுவலர் நியமிக்கப்படுவார்.',
    grievanceSubmitted: 'புகார் பதிவு செய்யப்பட்டது!',
    redirecting: 'உங்கள் புகார்களுக்கு அழைத்துச் செல்கிறோம்...',

    step1: 'உங்கள் விவரங்கள்', step2: 'பிரச்சனை விவரங்கள்', step3: 'ஆவணங்கள்', step4: 'சரிபார்த்து சமர்ப்பி',

    statusPending: 'பெறப்பட்டது',
    statusInProgress: 'ஆய்வில் உள்ளது',
    statusResolved: 'தீர்க்கப்பட்டது',
    statusRejected: 'நிராகரிக்கப்பட்டது',
    statusDescPending: 'உங்கள் புகார் பெறப்பட்டது, நியமிக்கப்படுவதற்கு காத்திருக்கிறது.',
    statusDescInProgress: 'ஒரு அலுவலர் தற்போது உங்கள் புகாரை ஆய்வு செய்கிறார்.',
    statusDescResolved: 'உங்கள் புகார் தீர்க்கப்பட்டது.',
    statusDescRejected: 'உங்கள் புகாரை செயல்படுத்த முடியவில்லை.',
    officerRemark: 'அலுவலரின் பதில்',
    submittedOn: 'சமர்ப்பிக்கப்பட்ட தேதி',
    refNumber: 'குறிப்பு எண்',

    draftSaved: 'வரைவு தானாக சேமிக்கப்பட்டது',
    continueDraft: 'நிறுத்திய இடத்திலிருந்து தொடரவா?',
    discardDraft: 'புதிதாக தொடங்கு',

    notifications: 'அறிவிப்புகள்',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    markAllRead: 'அனைத்தையும் படித்ததாக குறி',
    liteMode: 'லைட் மோட்',

    joinPlatform: 'இணைப்புக்கு வரவேற்கிறோம்',
    joinDesc: 'அரசு சேவைகளுக்கான உங்கள் ஒற்றை சாளரம்',
    citizenPortal: 'நான் ஒரு குடிமகன்',
    citizenPortalDesc: 'சேவைகளுக்கு விண்ணப்பிக்கவும், புகார்களை தெரிவிக்கவும்.',
    officerPortal: 'நான் ஒரு அரசு அலுவலர்',
    officerPortalDesc: 'கோரிக்கைகளை நிர்வகிக்கவும், புகார்களுக்கு பதிலளிக்கவும்.',
    fullName: 'முழு பெயர்',
    fullNamePlaceholder: 'உங்கள் அடையாள அட்டையில் உள்ளபடி',
    aadhaarNumber: 'ஆதார் எண்',
    password: 'கடவுச்சொல்',
    passwordHint: 'குறைந்தது 6 எழுத்துகள்',
    createAccount: 'கணக்கு உருவாக்கு',
    submitVerification: 'சரிபார்ப்புக்கு சமர்ப்பி',
    alreadyHaveAccount: 'ஏற்கனவே பதிவு செய்தீர்களா?',
    loginHere: 'இங்கே உள்நுழைக',
    pendingTitle: 'கோரிக்கை பெறப்பட்டது',
    pendingDesc: 'உங்கள் பதிவு நிர்வாகி ஒப்புதலுக்காக காத்திருக்கிறது.',
    backToLogin: 'உள்நுழைவுக்கு திரும்பு',

    trackTitle: 'உங்கள் புகாரை கண்காணி',
    trackDesc: 'புகார் ஐடியை உள்ளிடுங்கள் — உள்நுழைவு தேவையில்லை',
    trackPlaceholder: 'புகார் ஐடியை ஒட்டவும்...',
    trackButton: 'நிலையை சரிபார்',
    notFound: 'இந்த ஐடியில் புகார் கிடைக்கவில்லை.',
    assignedTo: 'நியமிக்கப்பட்டவர்',
    dept: 'துறை',
    noResults: 'பதிவுகள் எதுவும் இல்லை.',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');
  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;
  const switchLang = (l) => { setLang(l); localStorage.setItem('lang', l); };
  return <LangContext.Provider value={{ lang, t, switchLang }}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
